function [ Filter_Parts ] = FindSchmids
Filter_Parts{1}{1} = 'LoadingDirection';
Filter_Parts{2}{1} = 'FloatVec3Widget';
Filter_Parts{1}{2} = 'StoreAngleComponents';
Filter_Parts{2}{2} = 'LinkedBooleanWidget';
Filter_Parts{1}{3} = 'OverrideSystem';
Filter_Parts{2}{3} = 'LinkedBooleanWidget';
Filter_Parts{1}{4} = 'SlipPlane';
Filter_Parts{2}{4} = 'FloatVec3Widget';
Filter_Parts{1}{5} = 'SlipDirection';
Filter_Parts{2}{5} = 'FloatVec3Widget';
Filter_Parts{1}{6} = 'FeaturePhasesArrayPath';
Filter_Parts{2}{6} = 'DataArraySelectionWidget';
Filter_Parts{1}{7} = 'AvgQuatsArrayPath';
Filter_Parts{2}{7} = 'DataArraySelectionWidget';
Filter_Parts{1}{8} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{8} = 'DataArraySelectionWidget';
Filter_Parts{1}{9} = 'SchmidsArrayName';
Filter_Parts{2}{9} = 'StringWidget';
Filter_Parts{1}{10} = 'SlipSystemsArrayName';
Filter_Parts{2}{10} = 'StringWidget';
Filter_Parts{1}{11} = 'PolesArrayName';
Filter_Parts{2}{11} = 'StringWidget';
Filter_Parts{1}{12} = 'PhisArrayName';
Filter_Parts{2}{12} = 'StringWidget';
Filter_Parts{1}{13} = 'LambdasArrayName';
Filter_Parts{2}{13} = 'StringWidget';
end