function [ Filter_Parts ] = MergeTwins
Filter_Parts{1}{1} = 'AngleTolerance';
Filter_Parts{2}{1} = 'DoubleWidget';
Filter_Parts{1}{2} = 'AxisTolerance';
Filter_Parts{2}{2} = 'DoubleWidget';
Filter_Parts{1}{3} = 'UseNonContiguousNeighbors';
Filter_Parts{2}{3} = 'LinkedBooleanWidget';
Filter_Parts{1}{4} = 'NonContiguousNeighborListArrayPath';
Filter_Parts{2}{4} = 'DataArraySelectionWidget';
Filter_Parts{1}{5} = 'ContiguousNeighborListArrayPath';
Filter_Parts{2}{5} = 'DataArraySelectionWidget';
Filter_Parts{1}{6} = 'FeaturePhasesArrayPath';
Filter_Parts{2}{6} = 'DataArraySelectionWidget';
Filter_Parts{1}{7} = 'AvgQuatsArrayPath';
Filter_Parts{2}{7} = 'DataArraySelectionWidget';
Filter_Parts{1}{8} = 'FeatureIdsArrayPath';
Filter_Parts{2}{8} = 'DataArraySelectionWidget';
Filter_Parts{1}{9} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{9} = 'DataArraySelectionWidget';
Filter_Parts{1}{10} = 'CellParentIdsArrayName';
Filter_Parts{2}{10} = 'StringWidget';
Filter_Parts{1}{11} = 'NewCellFeatureAttributeMatrixName';
Filter_Parts{2}{11} = 'StringWidget';
Filter_Parts{1}{12} = 'FeatureParentIdsArrayName';
Filter_Parts{2}{12} = 'StringWidget';
Filter_Parts{1}{13} = 'ActiveArrayName';
Filter_Parts{2}{13} = 'StringWidget';
end