function [ Filter_Parts ] = WritePoleFigure
Filter_Parts{1}{1} = 'ImageFormat';
Filter_Parts{2}{1} = 'ChoiceWidget';
Filter_Parts{1}{2} = 'LambertSize';
Filter_Parts{2}{2} = 'IntWidget';
Filter_Parts{1}{3} = 'NumColors';
Filter_Parts{2}{3} = 'IntWidget';
Filter_Parts{1}{4} = 'ImageLayout';
Filter_Parts{2}{4} = 'ChoiceWidget';
Filter_Parts{1}{5} = 'ImagePrefix';
Filter_Parts{2}{5} = 'StringWidget';
Filter_Parts{1}{6} = 'OutputPath';
Filter_Parts{2}{6} = 'OutputPathWidget';
Filter_Parts{1}{7} = 'ImageSize';
Filter_Parts{2}{7} = 'IntWidget';
Filter_Parts{1}{8} = 'CellEulerAnglesArrayPath';
Filter_Parts{2}{8} = 'DataArraySelectionWidget';
Filter_Parts{1}{9} = 'CellPhasesArrayPath';
Filter_Parts{2}{9} = 'DataArraySelectionWidget';
Filter_Parts{1}{10} = 'GoodVoxelsArrayPath';
Filter_Parts{2}{10} = 'DataArraySelectionWidget';
Filter_Parts{1}{11} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{11} = 'DataArraySelectionWidget';
end