function [ Filter_Parts ] = FindLocalAverageCAxisMisalignments
Filter_Parts{1}{1} = 'CalcUnbiasedAvg';
Filter_Parts{2}{1} = 'LinkedBooleanWidget';
Filter_Parts{1}{2} = 'CalcBiasedAvg';
Filter_Parts{2}{2} = 'LinkedBooleanWidget';
Filter_Parts{1}{3} = 'NeighborListArrayPath';
Filter_Parts{2}{3} = 'DataArraySelectionWidget';
Filter_Parts{1}{4} = 'CAxisMisalignmentListArrayPath';
Filter_Parts{2}{4} = 'DataArraySelectionWidget';
Filter_Parts{1}{5} = 'FeatureIdsArrayPath';
Filter_Parts{2}{5} = 'DataArraySelectionWidget';
Filter_Parts{1}{6} = 'CellParentIdsArrayPath';
Filter_Parts{2}{6} = 'DataArraySelectionWidget';
Filter_Parts{1}{7} = 'AvgCAxisMisalignmentsArrayPath';
Filter_Parts{2}{7} = 'DataArraySelectionWidget';
Filter_Parts{1}{8} = 'FeatureParentIdsArrayPath';
Filter_Parts{2}{8} = 'DataArraySelectionWidget';
Filter_Parts{1}{9} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{9} = 'DataArraySelectionWidget';
Filter_Parts{1}{10} = 'NewCellFeatureAttributeMatrixName';
Filter_Parts{2}{10} = 'AttributeMatrixSelectionWidget';
Filter_Parts{1}{11} = 'NumFeaturesPerParentArrayName';
Filter_Parts{2}{11} = 'StringWidget';
Filter_Parts{1}{12} = 'UnbiasedLocalCAxisMisalignmentsArrayName';
Filter_Parts{2}{12} = 'StringWidget';
Filter_Parts{1}{13} = 'LocalCAxisMisalignmentsArrayName';
Filter_Parts{2}{13} = 'StringWidget';
end