function [ Filter_Parts ] = FindGBCD
Filter_Parts{1}{1} = 'GBCDRes';
Filter_Parts{2}{1} = 'DoubleWidget';
Filter_Parts{1}{2} = 'SurfaceMeshFaceLabelsArrayPath';
Filter_Parts{2}{2} = 'DataArraySelectionWidget';
Filter_Parts{1}{3} = 'SurfaceMeshFaceNormalsArrayPath';
Filter_Parts{2}{3} = 'DataArraySelectionWidget';
Filter_Parts{1}{4} = 'SurfaceMeshFaceAreasArrayPath';
Filter_Parts{2}{4} = 'DataArraySelectionWidget';
Filter_Parts{1}{5} = 'FeatureEulerAnglesArrayPath';
Filter_Parts{2}{5} = 'DataArraySelectionWidget';
Filter_Parts{1}{6} = 'FeaturePhasesArrayPath';
Filter_Parts{2}{6} = 'DataArraySelectionWidget';
Filter_Parts{1}{7} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{7} = 'DataArraySelectionWidget';
Filter_Parts{1}{8} = 'FaceEnsembleAttributeMatrixName';
Filter_Parts{2}{8} = 'StringWidget';
Filter_Parts{1}{9} = 'GBCDArrayName';
Filter_Parts{2}{9} = 'StringWidget';
end