function [ Filter_Parts ] = MicrotextureFatigueAnalysis
Filter_Parts{1}{1} = 'StressAxis';
Filter_Parts{2}{1} = 'FloatVec3Widget';
Filter_Parts{1}{2} = 'InitiatorLowerThreshold';
Filter_Parts{2}{2} = 'DoubleWidget';
Filter_Parts{1}{3} = 'InitiatorUpperThreshold';
Filter_Parts{2}{3} = 'DoubleWidget';
Filter_Parts{1}{4} = 'PropagatorLowerThreshold';
Filter_Parts{2}{4} = 'DoubleWidget';
Filter_Parts{1}{5} = 'PropagatorUpperThreshold';
Filter_Parts{2}{5} = 'DoubleWidget';
Filter_Parts{1}{6} = 'CellFeatureAttributeMatrixName';
Filter_Parts{2}{6} = 'AttributeMatrixSelectionWidget';
Filter_Parts{1}{7} = 'EulerAnglesArrayPath';
Filter_Parts{2}{7} = 'DataArraySelectionWidget';
Filter_Parts{1}{8} = 'PhasesArrayPath';
Filter_Parts{2}{8} = 'DataArraySelectionWidget';
Filter_Parts{1}{9} = 'NeighborListArrayPath';
Filter_Parts{2}{9} = 'DataArraySelectionWidget';
Filter_Parts{1}{10} = 'CrystalStructuresArrayPath';
Filter_Parts{2}{10} = 'DataArraySelectionWidget';
Filter_Parts{1}{11} = 'InitiatorsArrayName';
Filter_Parts{2}{11} = 'StringWidget';
Filter_Parts{1}{12} = 'PropagatorsArrayName';
Filter_Parts{2}{12} = 'StringWidget';
Filter_Parts{1}{13} = 'BadActorsArrayName';
Filter_Parts{2}{13} = 'StringWidget';
end