function [ Filter_Parts ] = PackPrimaryPhases
Filter_Parts{1}{1} = 'PeriodicBoundaries';
Filter_Parts{2}{1} = 'BooleanWidget';
Filter_Parts{1}{2} = 'InputStatsArrayPath';
Filter_Parts{2}{2} = 'DataArraySelectionWidget';
Filter_Parts{1}{3} = 'InputPhaseTypesArrayPath';
Filter_Parts{2}{3} = 'DataArraySelectionWidget';
Filter_Parts{1}{4} = 'InputShapeTypesArrayPath';
Filter_Parts{2}{4} = 'DataArraySelectionWidget';
Filter_Parts{1}{5} = 'OutputCellAttributeMatrixName';
Filter_Parts{2}{5} = 'AttributeMatrixSelectionWidget';
Filter_Parts{1}{6} = 'OutputCellFeatureAttributeMatrixName';
Filter_Parts{2}{6} = 'StringWidget';
Filter_Parts{1}{7} = 'OutputCellEnsembleAttributeMatrixName';
Filter_Parts{2}{7} = 'StringWidget';
Filter_Parts{1}{8} = 'FeatureIdsArrayName';
Filter_Parts{2}{8} = 'StringWidget';
Filter_Parts{1}{9} = 'CellPhasesArrayName';
Filter_Parts{2}{9} = 'StringWidget';
Filter_Parts{1}{10} = 'FeaturePhasesArrayName';
Filter_Parts{2}{10} = 'StringWidget';
Filter_Parts{1}{11} = 'NumFeaturesArrayName';
Filter_Parts{2}{11} = 'StringWidget';
Filter_Parts{1}{12} = 'WriteGoalAttributes';
Filter_Parts{2}{12} = 'LinkedBooleanWidget';
Filter_Parts{1}{13} = 'CsvOutputFile';
Filter_Parts{2}{13} = 'OutputFileWidget';
end