function [ Filter_Parts ] = ParaDisReader
Filter_Parts{1}{1} = 'InputFile';
Filter_Parts{2}{1} = 'InputFileWidget';
Filter_Parts{1}{2} = 'BurgersVector';
Filter_Parts{2}{2} = 'DoubleWidget';
Filter_Parts{1}{3} = 'EdgeDataContainerName';
Filter_Parts{2}{3} = 'StringWidget';
Filter_Parts{1}{4} = 'VertexAttributeMatrixName';
Filter_Parts{2}{4} = 'StringWidget';
Filter_Parts{1}{5} = 'EdgeAttributeMatrixName';
Filter_Parts{2}{5} = 'StringWidget';
Filter_Parts{1}{6} = 'NumberOfArmsArrayName';
Filter_Parts{2}{6} = 'StringWidget';
Filter_Parts{1}{7} = 'NodeConstraintsArrayName';
Filter_Parts{2}{7} = 'StringWidget';
Filter_Parts{1}{8} = 'BurgersVectorsArrayName';
Filter_Parts{2}{8} = 'StringWidget';
Filter_Parts{1}{9} = 'SlipPlaneNormalsArrayName';
Filter_Parts{2}{9} = 'StringWidget';
end