function [ Filter_Parts ] = QuickSurfaceMesh
Filter_Parts{1}{1} = 'TransferPhaseId';
Filter_Parts{2}{1} = 'LinkedBooleanWidget';
Filter_Parts{1}{2} = 'FeatureIdsArrayPath';
Filter_Parts{2}{2} = 'DataArraySelectionWidget';
Filter_Parts{1}{3} = 'CellPhasesArrayPath';
Filter_Parts{2}{3} = 'DataArraySelectionWidget';
Filter_Parts{1}{4} = 'SurfaceDataContainerName';
Filter_Parts{2}{4} = 'StringWidget';
Filter_Parts{1}{5} = 'VertexAttributeMatrixName';
Filter_Parts{2}{5} = 'StringWidget';
Filter_Parts{1}{6} = 'FaceAttributeMatrixName';
Filter_Parts{2}{6} = 'StringWidget';
Filter_Parts{1}{7} = 'FaceLabelsArrayName';
Filter_Parts{2}{7} = 'StringWidget';
Filter_Parts{1}{8} = 'NodeTypesArrayName';
Filter_Parts{2}{8} = 'StringWidget';
Filter_Parts{1}{9} = 'FacePhasesArrayName';
Filter_Parts{2}{9} = 'StringWidget';
end