function [ Filter_Parts ] = UncertainRegularGridSampleSurfaceMesh
Filter_Parts{1}{1} = 'SurfaceMeshFaceLabelsArrayPath';
Filter_Parts{2}{1} = 'DataArraySelectionWidget';
Filter_Parts{1}{2} = 'XPoints';
Filter_Parts{2}{2} = 'IntWidget';
Filter_Parts{1}{3} = 'YPoints';
Filter_Parts{2}{3} = 'IntWidget';
Filter_Parts{1}{4} = 'ZPoints';
Filter_Parts{2}{4} = 'IntWidget';
Filter_Parts{1}{5} = 'Resolution';
Filter_Parts{2}{5} = 'FloatVec3Widget';
Filter_Parts{1}{6} = 'Uncertainty';
Filter_Parts{2}{6} = 'FloatVec3Widget';
Filter_Parts{1}{7} = 'DataContainerName';
Filter_Parts{2}{7} = 'StringWidget';
Filter_Parts{1}{8} = 'CellAttributeMatrixName';
Filter_Parts{2}{8} = 'StringWidget';
Filter_Parts{1}{9} = 'FeatureIdsArrayName';
Filter_Parts{2}{9} = 'StringWidget';
end